version: '3.8'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: txlab
      MYSQL_USER: txlab
      MYSQL_PASSWORD: txlab
      MYSQL_ROOT_PASSWORD: txlab
    ports:
      - "3316:3306"
