spring:
  datasource:
    url: jdbc:postgresql://localhost:5439/txlab
    username: txlab
    password: txlab
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    com.example.txlab: DEBUG
